crds:
  enabled: true
currentNamespaceOnly: true
logLevel: INFO
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: "1"
    memory: 512Mi
allowLoopDevices: false
enableDiscoveryDaemon: false
monitoring:
  enabled: true
csi:
  installCsiOperator: true
  serviceMonitor:
    enabled: true
    namespace: rook-ceph
