crds:
  enabled: true
currentNamespaceOnly: true
logLevel: INFO
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: "1"
    memory: 512Mi
allowLoopDevices: false
enableDiscoveryDaemon: false
monitoring:
  enabled: true
ceph-csi-operator:
  controllerManager:
    manager:
      env:
        csiServiceAccountPrefix: ""
        watchNamespace: rook-ceph
csi:
  installCsiOperator: true
  cephcsi:
    repository: quay.io/cephcsi/cephcsi
    tag: v3.17.1
  serviceMonitor:
    enabled: true
    namespace: rook-ceph
