apiVersion: v1
kind: Namespace
metadata:
  name: sops-system
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  labels:
    app.kubernetes.io/part-of: playbox-platform
    playbox.dev/sops-key-domain: platform
    playbox.dev/sops-domain: platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  labels:
    app.kubernetes.io/part-of: playbox-platform
    playbox.dev/sops-domain: platform
